---
- name: Tworzymy katalog do budowy obrazu
  ansible.builtin.file:
    path: /mpedzicki/demo-dockerfile
    state: directory
    owner: mpedzicki
    group: mpedzicki
    mode: '0755'

- name: Kopiujemy plik Dockerfile
  ansible.builtin.copy:
    src: ./roles/nginx_role/files/Dockerfile
    owner: mpedzicki
    group: mpedzicki
    mode: '0755'
    dest: /mpedzicki/demo-dockerfile/Dockerfile

- name: Kopiowanie pliku default.conf
  ansible.builtin.template:
    src: ./roles/nginx_role/templates/default.conf.j2
    owner: mpedzicki
    group: mpedzicki
    mode: '0755'
    dest: /mpedzicki/demo-dockerfile/default.conf
  vars:
    message: "{{ nginx_role_custom_message | default('OK') }}"

- name: Zatrzymujemy kontener
  community.docker.docker_container:
    name: alter-nginx
    state: absent

- name: Usuwamy obraz
  community.docker.docker_image:
    name: test-nginx
    state: absent

- name: Budowa obrazu Docker
  community.docker.docker_image:
    name: test-nginx
    build:
      path: /mpedzicki/demo-dockerfile
    source: build
    state: present
    tag: latest

- name: Start kontenera
  community.docker.docker_container:
    name: alter-nginx
    image: test-nginx:latest
    state: started
    ports:
      - "127.0.0.1:80:80"
#    volumes:
#      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
